### ISSUE TITLE
Can not find struct HTTP_HaderTypeDef

### ISSUE THREAD

**Issue by zx310** [MrZahaki/GSM#1]
Hi, Bro.
Thanks for your  codes. But i compiled it failed, Some struct may not found in codes.

**Comment by mrzahaki** [comment]
Hi there, I’m glad you liked my codes. I apologize for the inconvenience caused by the missing struct. I have fixed the problem and pushed the new changes to my github. Please pull the latest version and try to compile it again. Let me know if you encounter any other issues or have any feedback. Thank you for your interest in my project. Cheers! 😊
